"""add receipt_path to expenses

Revision ID: 14faea48172e
Revises: 64d26ad89d64
Create Date: 2026-07-02 20:28:17.085930

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '14faea48172e'
down_revision: Union[str, Sequence[str], None] = '64d26ad89d64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('receipt_path', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('expenses', 'receipt_path')
    # ### end Alembic commands ###
