"""add employee profile fields

Revision ID: 3da8f77cfea6
Revises: ca4de5845964
Create Date: 2026-07-10 17:41:24.820338

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3da8f77cfea6'
down_revision: Union[str, Sequence[str], None] = 'ca4de5845964'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('users', sa.Column('employee_id', sa.String(length=30), nullable=True))
    op.add_column('users', sa.Column('phone', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('gender', sa.String(length=20), nullable=True))
    op.add_column('users', sa.Column('location', sa.String(length=150), nullable=True))
    op.add_column('users', sa.Column('birth_date', sa.Date(), nullable=True))
    op.add_column('users', sa.Column('date_of_joining', sa.Date(), nullable=True))
    op.create_unique_constraint(None, 'users', ['employee_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'users', type_='unique')
    op.drop_column('users', 'date_of_joining')
    op.drop_column('users', 'birth_date')
    op.drop_column('users', 'location')
    op.drop_column('users', 'gender')
    op.drop_column('users', 'phone')
    op.drop_column('users', 'employee_id')
    # ### end Alembic commands ###
