"""add expense approval history

Revision ID: 9138dff2fb1a
Revises: f447ef7fc738
Create Date: 2026-07-06 16:08:48.435621

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '9138dff2fb1a'
down_revision: Union[str, Sequence[str], None] = 'f447ef7fc738'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('approved_by', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('approved_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('expenses', sa.Column('rejected_by', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('rejected_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('expenses', sa.Column('rejection_reason', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'expenses', 'users', ['rejected_by'], ['id'])
    op.create_foreign_key(None, 'expenses', 'users', ['approved_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'rejection_reason')
    op.drop_column('expenses', 'rejected_at')
    op.drop_column('expenses', 'rejected_by')
    op.drop_column('expenses', 'approved_at')
    op.drop_column('expenses', 'approved_by')
    # ### end Alembic commands ###
