"""add payment fields to expenses

Revision ID: ffb593257d19
Revises: 9138dff2fb1a
Create Date: 2026-07-08 10:51:37.594446

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ffb593257d19'
down_revision: Union[str, Sequence[str], None] = '9138dff2fb1a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('expenses', sa.Column('paid_by', sa.String(), nullable=True))
    op.add_column('expenses', sa.Column('paid_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('expenses', sa.Column('payment_reference', sa.String(length=200), nullable=True))
    op.add_column('expenses', sa.Column('payment_notes', sa.String(length=500), nullable=True))
    op.create_foreign_key(None, 'expenses', 'users', ['paid_by'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'expenses', type_='foreignkey')
    op.drop_column('expenses', 'payment_notes')
    op.drop_column('expenses', 'payment_reference')
    op.drop_column('expenses', 'paid_at')
    op.drop_column('expenses', 'paid_by')
    # ### end Alembic commands ###
